//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebsiteForParadigms.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LabServiceSoap", Namespace="http://tempuri.org/")]
    public partial class LabService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Lab1_22OperationCompleted;
        
        private System.Threading.SendOrPostCallback Lab1_51OperationCompleted;
        
        private System.Threading.SendOrPostCallback Lab2_4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Lab3_7OperationCompleted;
        
        private System.Threading.SendOrPostCallback Lab4_5OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LabService() {
            this.Url = global::WebsiteForParadigms.Properties.Settings.Default.WebsiteForParadigms_localhost_LabService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Lab1_22CompletedEventHandler Lab1_22Completed;
        
        /// <remarks/>
        public event Lab1_51CompletedEventHandler Lab1_51Completed;
        
        /// <remarks/>
        public event Lab2_4CompletedEventHandler Lab2_4Completed;
        
        /// <remarks/>
        public event Lab3_7CompletedEventHandler Lab3_7Completed;
        
        /// <remarks/>
        public event Lab4_5CompletedEventHandler Lab4_5Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lab1_22", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] Lab1_22(int[] input) {
            object[] results = this.Invoke("Lab1_22", new object[] {
                        input});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void Lab1_22Async(int[] input) {
            this.Lab1_22Async(input, null);
        }
        
        /// <remarks/>
        public void Lab1_22Async(int[] input, object userState) {
            if ((this.Lab1_22OperationCompleted == null)) {
                this.Lab1_22OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLab1_22OperationCompleted);
            }
            this.InvokeAsync("Lab1_22", new object[] {
                        input}, this.Lab1_22OperationCompleted, userState);
        }
        
        private void OnLab1_22OperationCompleted(object arg) {
            if ((this.Lab1_22Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lab1_22Completed(this, new Lab1_22CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lab1_51", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] Lab1_51(int[] input) {
            object[] results = this.Invoke("Lab1_51", new object[] {
                        input});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void Lab1_51Async(int[] input) {
            this.Lab1_51Async(input, null);
        }
        
        /// <remarks/>
        public void Lab1_51Async(int[] input, object userState) {
            if ((this.Lab1_51OperationCompleted == null)) {
                this.Lab1_51OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLab1_51OperationCompleted);
            }
            this.InvokeAsync("Lab1_51", new object[] {
                        input}, this.Lab1_51OperationCompleted, userState);
        }
        
        private void OnLab1_51OperationCompleted(object arg) {
            if ((this.Lab1_51Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lab1_51Completed(this, new Lab1_51CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lab2_4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] Lab2_4(int[] input) {
            object[] results = this.Invoke("Lab2_4", new object[] {
                        input});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void Lab2_4Async(int[] input) {
            this.Lab2_4Async(input, null);
        }
        
        /// <remarks/>
        public void Lab2_4Async(int[] input, object userState) {
            if ((this.Lab2_4OperationCompleted == null)) {
                this.Lab2_4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLab2_4OperationCompleted);
            }
            this.InvokeAsync("Lab2_4", new object[] {
                        input}, this.Lab2_4OperationCompleted, userState);
        }
        
        private void OnLab2_4OperationCompleted(object arg) {
            if ((this.Lab2_4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lab2_4Completed(this, new Lab2_4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lab3_7", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Lab3_7(string w) {
            this.Invoke("Lab3_7", new object[] {
                        w});
        }
        
        /// <remarks/>
        public void Lab3_7Async(string w) {
            this.Lab3_7Async(w, null);
        }
        
        /// <remarks/>
        public void Lab3_7Async(string w, object userState) {
            if ((this.Lab3_7OperationCompleted == null)) {
                this.Lab3_7OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLab3_7OperationCompleted);
            }
            this.InvokeAsync("Lab3_7", new object[] {
                        w}, this.Lab3_7OperationCompleted, userState);
        }
        
        private void OnLab3_7OperationCompleted(object arg) {
            if ((this.Lab3_7Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lab3_7Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lab4_5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public char[] Lab4_5() {
            object[] results = this.Invoke("Lab4_5", new object[0]);
            return ((char[])(results[0]));
        }
        
        /// <remarks/>
        public void Lab4_5Async() {
            this.Lab4_5Async(null);
        }
        
        /// <remarks/>
        public void Lab4_5Async(object userState) {
            if ((this.Lab4_5OperationCompleted == null)) {
                this.Lab4_5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLab4_5OperationCompleted);
            }
            this.InvokeAsync("Lab4_5", new object[0], this.Lab4_5OperationCompleted, userState);
        }
        
        private void OnLab4_5OperationCompleted(object arg) {
            if ((this.Lab4_5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lab4_5Completed(this, new Lab4_5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Lab1_22CompletedEventHandler(object sender, Lab1_22CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lab1_22CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lab1_22CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Lab1_51CompletedEventHandler(object sender, Lab1_51CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lab1_51CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lab1_51CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Lab2_4CompletedEventHandler(object sender, Lab2_4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lab2_4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lab2_4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Lab3_7CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Lab4_5CompletedEventHandler(object sender, Lab4_5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lab4_5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lab4_5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public char[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((char[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591